### PR TITLE
Added `units` to Latex

### PR DESCRIPTION
**Pull request by hamogu**
This should resolve issue 23, but I don't know how I can attach a pull request to an issue (because I did not spend enough time to learn how to use github properly).

### CODE REVIEW

**Comment by taldcroft** [comment]
Looks good.  Just one question, can you confirm that you latexed the deluxetable test_write output and that is gives the desired result?

**Comment by hamogu** [comment]
There are two issues:
- LaTeX failes, because of the "no_error" values (Missing $ inserted). That's a problem with the values in the table used in test_write, not with asciitable.AASTex itself.
- The lines in the table do not come out right in the ps for the standard LaTeX table with `emulateapj` or `AASTeX`: Again, this is not a problem with asciitable.AASTex but with emulateapj (or the AAS style file). Just use `deluxetable' for AAS publications and normal LaTeX for other style files.

So the answer is "No, you cannot latex my example directly, but YES, the code output is OK". It's just LaTeX itself with has problems with this particular example.

**Comment by taldcroft** [comment]
@hamogu -- Looks like this introduced regression failures in nosetest.  Can you have a look?

**Comment by hamogu** [comment]
I suggest to fix it exactly the way you did in your commit.
This issue is the following: `asciitable.latex.latexdicts['template']` now has a key `units` and if the LaTeX writer finds a key `units`, then it writes a line in the header with values for the units. However, in the specific case that line is empty, since none of the column names in `asciitable.latex.latexdicts['template']` matches any column name in the test table printed by the regression tests. I did not catch that before I submitted my pull request, because I did not run the regression tests (a system update had screwed up my nose installation).

However, thinking about it again, I see this as a feature and not a bug. Generally, users will consciously construct the `latexdict` which sets the option for LaTeX output. If the user makes a dictionary with a key `units` he gets a line with units. That line could be empty, because the user deliberately did not enter column names that match the table. Use cases could be:
- The user wants to paste complicated LaTeX code with plenty of special characters directly in the tex file without worrying about escaping those characters in his python script.
- The units line is actually empty in this table, but should be present to obtain a consistent layout over several tables.

Even if the user just mistyped the `{'columnname': 'columnunit'}` dictionary it is useful to output the units line - it shows that the output works, but there is some mismatch to the column names.

**Comment by hamogu** [comment]
My version of the fix is actually identical to yours. See comment above for my reasoning.

**Pull request merged**
