### PR TITLE
LaTeX input and output

### PR DESCRIPTION
**Pull request by hamogu**
Hi,
I added a class for output in LaTeX. It also reads simple LaTeX tables, as long as they are reasonable (one line for each row of data, no multicolumn or something like that).
The main purpose however is writing in LaTeX, because that allow a for a fully scripted production of tables from dataset with python and asciitable.
Most of my work actually went into reading, but I expect to be much less used in practice.

In the course of the implementation I discovered two bugs, which are only relevant, if `start_values` and `end_values` are realized as functions (which very few people use, I expect). I put long comments in the commit messages, so please check there or ask me, when in doubt.

Also, I added a mechanism, where the Reader or Writer class can allow extra keywords for `asciitable.read` or `asciitable.write`.
In the case of Latex, is makes sense e.g. to give a caption for the table output.

### CODE REVIEW

**Comment by hamogu** [comment]
I should add, that I added unit tests already, but no documentation. However, I am happy to write that as well, if you decide to pull this change. I just don't want to document something now and then later you decide to change the API.

**Comment by taldcroft** [comment]
I'm looking at this.  You might notice that I (belatedly) pushed a new branch "refactor" that is a major refactor of asciitable into more manageable modules, so that will be a complication.  I'm enthusiastic about your addition, I think it is a valuable new functionality.

**Comment by taldcroft** [comment]
"Also, I added a mechanism, where the Reader or Writer class can allow extra keywords for asciitable.read or asciitable.write."

I also did this in my recent development, it was clearly needed... sigh.

**Comment by hamogu** [comment]
Please pull the current `LaTeX` branch to ensure that we stay in sync. (And to check the the merging really works.)

**Comment by taldcroft** [comment]
Done, hamogu:LaTeX merged with taldcroft:refactor_latex.  For my own future reference:
git checkout refactor_latex
git pull hamogu LaTeX
git push origin refactor_latex

**Pull request merged**
