### PR TITLE
CDS header from ReadMe file supplied by Vizier.

### PR DESCRIPTION
**Pull request by phn**
Hello,

Vizier supplies CDS format tables with header information in a separate file named `ReadMe`. I have added some code so that we can now read the header information for a CDS table from this `ReadMe`. This means there is no need to insert the header information into the table file. 

The following is the log message of the last but one commit in the `cds_header_from_readme` branch. The last commit is a merge commit.

```
Read Cds table with header taken from a ReadMe file.

When ``Cds`` reader object is created with a
``readme`` parameter passed to it at initialization, then when
the ``read`` method is executed with a table filename, the header
information for the specified table is taken from the ``readme`` file.
An ``IncosistentTableError`` is raised if the ``readme`` file does not
have header information for the given table.

    >>> readme = "t/vizier/ReadMe"
    >>> r = asciitable.Cds(readme)
    >>> table = r.read("t/vizier/table1.dat")

At initialization, ``CdsHeader`` stores name of "ReadMe" file in
``self.readme``. This initialization takes place when the ``Cds``
class is initialized to get a new reader.

When ``read`` is invoked ``BaseReader`` stores name of table filename
in ``self.data.table_name``; only if ``table`` is a file.

Within ``CdsData`` the ``get_data_lines`` function checks to see if
``self.table_name`` and ``self.header.readme`` are true and if so,
the step of skipping over the header information in ``lines``
is skipped. The ``lines`` attribute will not have any header information.

Within ``CdsHeader`` the ``get_cols`` method checks to see if both
``self.readme`` and ``self.data.filename`` are true. If they are, then
the ``lines`` parameter is ignored and a new ``lines`` list is
read from ``self.readme`` and will contain only the header of the
``self.data.table_name`` table. Parsing of this set of lines takes place
as usual.

Since ``self.data.table_name`` and ``self.header.readme`` of the ``Cds``
reader are set to None by default, if not ``readme`` is specified at
initialization, then the regular parsing of the table takes place.
Therefore any previous code that uses ``Cds`` reader will continue to
work.
```

### CODE REVIEW

**Comment by taldcroft** [comment]
This looks good, thanks!  I will have a closer look at the patch this weekend and plan to put out a new release shortly.

**Comment by taldcroft** [comment]
I've looked at the code in detail and generally things look good.  Comments / requests:
- The long commit message ("When `Cds` reader object is created with...") is good documentation on the new functionality and should be integrated into the existing class Cds docstring.
- Running "nosetests" fails for 3 tests.  Two failures are from this new code that throws an uncaught exception if `table` is not string-like.  Probably just need to `try` and catch a `TypeError` exception (with pass on exception):
  
  ```
  # If ``table`` is a file then store the name in the ``data``
  # attribute. 
  if os.linesep not in table + '':
      self.data.table_name = os.path.basename(table)
  ```
- One failure is `AttributeError: 'CdsHeader' object has no attribute 'splitter'` which I have not looked into.

**Comment by phn** [comment]
I failed to run the full `nosetests` suite since I was lulled into a false sense of security by the success of `test_cds_header_from_readme.py` !

> > The long commit message ("When Cds reader object is created with...")
> > is good documentation on the new functionality and should be integrated
> > into the existing class Cds docstring.

I have entered the log message in the `Cds` class docstring; only the part relevant to the user.

> > Running "nosetests" fails for 3 tests. Two failures are from this new
> > code that throws an uncaught exception if table is not
> > string-like. Probably just need to try and catch a TypeError exception
> > (with pass on exception):
> > 
> >   # If `table` is a file then store the name in the `data`
> >   # attribute. 
> >   if os.linesep not in table + '':
> >       self.data.table_name = os.path.basename(table)

Yes, I should have done that. I was imitating the code in `BaseInputter.get_lines`, but forgot to put the `try ... except` block. I have added the `try ... except` block.

> > One failure is AttributeError: 'CdsHeader' object has no attribute
> > 'splitter' which I have not looked into.

I had added an `__init__` method to `CdsHeader`, but forgot to call the `__init__` method of the `BaseHeader` class, which is the super class of `CdsHeader`. The splitter is initialized there and hence wasn't being created. I have fixed it. 

When `get_reader` is not used, then the `splitter` property is not used at all since the `CdsHeader.get_cols` function doesn't use the `splitter`. It either directly parses the lines or reads the "ReadMe" and parses those lines. When `get_reader` function is used, this function explicitly sets the `delimiter` property of the `splitter`. This raises `AttributeError`, since `splitter` hasn't been set by the `CdsHeader.__init__` method.

Now `nosetests` runs without any failures:

```
 $ nosetests test/
 .......................................................
 ----------------------------------------------------------------------
Ran 55 tests in 0.557s

OK
```

**Comment by phn** [comment]
Hello,

I just noticed that I had forgotten to delete a `print` statement in `asciitable.py`. This showed up only when I tried to run `nosetests`  under Python3. I have deleted the line, line 827, and have made a commit and confirmed that all tests pass.

Sorry about that.

I have tested the code only with Python 2.6 and Python 3.1.

**Pull request merged**
